FROM ubuntu:18.04

RUN apt-get update && apt-get install --assume-yes \
    libssl-dev libglib2.0-dev libcairo2-dev libpango1.0-dev \
    libatk1.0-dev libgdk-pixbuf2.0-dev libsoup2.4-dev \
    libgtk-3-dev libwebkit2gtk-4.0-dev curl wget build-essential